# This is a basic workflow to help you get started with Actions

name: Check accessability of host

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron:  '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check geniusserg.github.io
      run: ping -n 1 geniusserg.github.io

