name: Course Work CI/CD

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  test_main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Launch local server
      run: docker run -v $GITHUB_WORKSPACE/html:/usr/share/nginx/html:ro  -p 8080:80 -d nginx
    - name: Ping web page
      run: curl -l http://localhost:8080/index.html
    - name: Run the testing image with web driver Chrome
      run: docker run ubuntu:latest wget http://localhost:8080
    - name: Run the testing image with web driver Chrome
      run: docker run -w /work --network=host -v /dev/shm:/dev/shm -v $GITHUB_WORKSPACE/tests:/work joyzoursky/python-chromedriver:3.7-alpine3.8-selenium curl http://localhost:8080
  deploy:
    runs-on: ubuntu-latest
    needs: [test_main]
    steps:
    - uses: actions/checkout@v2
    - name: Create dockerfile
      run: |
        cd html
        docker build -t ${{ secrets.DOCKER_USERNAME }}/car_config:latest .
    - name: Deploy ready package for further manual testing
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin;   docker push  ${{ secrets.DOCKER_USERNAME }}/car_config:latest

