name: Course Work CI/CD

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  test_main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Launch local server
      run: docker run --network=host -v $GITHUB_WORKSPACE/html:/usr/share/nginx/html:ro  -p 8080:80 -d nginx
    - name: Run the testing image with web driver Chrome
      run: docker run --network=host -w /work -p 4444:4444 -p 8080:8080 -v /dev/shm:/dev/shm -v $GITHUB_WORKSPACE/tests:/work joyzoursky/python-chromedriver:3.7-alpine3.8-selenium python3 ./test.py
  deploy:
    runs-on: ubuntu-latest
    needs: [test_main]
    steps:
    - uses: actions/checkout@v2
    - name: Create dockerfile
      run: |
        cd html
        docker build -t ${{ secrets.DOCKER_USERNAME }}/car_config:latest .
    - name: Deploy ready package for further manual testing
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin;   docker push  ${{ secrets.DOCKER_USERNAME }}/car_config:latest

