name: Course Work CI/CD

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  test_main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Launch local server
      run: docker run -v $GITHUB_WORKSPACE/html:/usr/share/nginx/html:ro  -p 8080:80 -d nginx
    - name: Ping web page
      run: curl -l http://localhost:8080/index.html
    - name: Download Chrome Browser
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install google-chrome-stable
    - name: Download Chrome Driver
      run: |
        curl https://chromedriver.storage.googleapis.com/79.0.3945.36/chromedriver_linux64.zip 
        unzip chromedriver_linux64.zip -d /opt/chrome_driver
        ls /opt/chrome_driver
        chmod +x /opt/chrome_driver/chromedriver
  deploy:
    runs-on: ubuntu-latest
    needs: [test_main]
    steps:
    - uses: actions/checkout@v2
    - name: Create dockerfile
      run: |
        cd html
        docker build -t ${{ secrets.DOCKER_USERNAME }}/car_config:latest .
    - name: Deploy ready package for further manual testing
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin;   docker push  ${{ secrets.DOCKER_USERNAME }}/car_config:latest

