name: Course Work CI/CD

on:
  push:
    branches: master, develop
  pull_request:
    branches: master, develop

jobs:
  test_main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Launch local server
      run: docker run -v /home/runner/work/coursework/coursework/html:/usr/share/nginx/html:ro  -p 8080:80 -d nginx
    - name: Try to connect local server
      run: ping -p 8080 localhost
    - name: Run the testing image with web driver Chrome
      run: docker run -p 4444:4444 -p 80:80 -v /dev/shm:/dev/shm -v /home/runner/work/coursework/coursework/tests:/work selenium/standalone-chrome:3.141.59-20200409 python3 -m unittest -v /work/test.py
      
  deploy:
    runs-on: ubuntu-latest
    needs: [test_main]
    steps:
    - uses: actions/checkout@v2
    - name: Create dockerfile
      run: |
        cd html
        echo "FROM nginx" > Dockerfile
        echo "COPY . /usr/share/nginx/html" > Dockerfile
        docker build -t ${{ secrets.DOCKER_USERNAME }}/car_config:$GITHUB_REF .
    - name: Deploy ready package for further manual testing
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin;   docker push  ${{ secrets.DOCKER_USERNAME }}/car_config:$GITHUB_REF

