name: Course Work CI/CD

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  test_main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Launch local server with page
      run: |
        cp -r include ./html
        cp *.html ./html
        cp *.htm ./html
        cp *.pdf ./html
        docker run -v $GITHUB_WORKSPACE/html:/usr/share/nginx/html:ro  -p 8080:80 -d nginx
    - name: Ping web page on adress localhost:8080
      run: curl -I http://localhost:8080/index.html
    - name: Download Chrome Driver for selenium
      run: |
        curl -O https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip 
        unzip chromedriver_linux64.zip -d /opt/chrome_driver
        ls /opt/chrome_driver
        chmod +x /opt/chrome_driver/chromedriver
        export PATH=$PATH:/opt/chrome_driver/chromedriver;
    - name: Install selenium for python
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install selenium
        python3 -m pip install outcome
    - name: Run Tests
      run: |
        cd tests
        touch test.log
        touch err.log
        python3 -m unittest rt 1>msg.log || set LAST=$? && cat msg.log >> test.log
        echo $LAST
        if [ "$LAST" = "1" ]; then
          cd iyrtuiu
        fi
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: testing result
        path: tests/test.log


