name: Course Work CI/CD

on:
  pull_request:
    branches: master

jobs:
  test_main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Launch local server with page
      run: |
        cp -r include ./html
        cp -r index.html ./html
        docker run -v $GITHUB_WORKSPACE/html:/usr/share/nginx/html:ro  -p 8080:80 -d nginx
    - name: Ping web page on adress localhost:8080
      run: curl -I http://localhost:8080/index.html
    - name: Download Chrome Browser
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install google-chrome-stable
    - name: Download Chrome Driver for selenium
      run: |
        curl -O https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip 
        unzip chromedriver_linux64.zip -d /opt/chrome_driver
        ls /opt/chrome_driver
        chmod +x /opt/chrome_driver/chromedriver
        export PATH=$PATH:/opt/chrome_driver/chromedriver;
    - name: Install selenium for python
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install selenium
    - name: Run Tests
      run: |
        cd tests 
        python3 -m unittest
      
