name: Course Work CI/CD

on:
  pull_request:
    branches: master

jobs:
  test_main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Launch local server with page
      run: |
        cp -r include ./html
        cp -r index.html ./html
        docker run -v $GITHUB_WORKSPACE/html:/usr/share/nginx/html:ro  -p 8080:80 -d nginx
    - name: Ping web page on adress localhost:8080
      run: curl -I http://localhost:8080/index.html
    - name: Install selenium for python
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install selenium
    - name: Run Tests
      run: |
        cd tests 
        python3 -m unittest
      
